plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.dep.bluestarbridge'
    compileSdk 35

    defaultConfig {
        applicationId 'dev.dep.bluestarbridge'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '0.2.1-local-lan'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.github.EspressifApp:lib-blufi-android:2.3.7'
}
